
name: Coverity4spdk

#Run on push
on:
  push:
    branches:
      - master
#Run once a day
#on:
#  schedule:
#    - cron:  '20 0 * * *'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install submodule
      run: |
        date 
        git submodule update --init
    - name: install Prerequisites
      run: |
        date 
        sudo ./scripts/pkgdep.sh
    - name: config
      run: |
        date 
        ./configure
    - name: tool download
      run: |
        time wget https://scan.coverity.com/download/linux64 \
             --post-data "token=${{ secrets.COVERITY_TOKEN_SPDK }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
             --progress=dot:giga -O coverity_tool.tgz
    - name: tool install
      run: |
        ls -alh coverity_tool.tgz
        time tar xzf coverity_tool.tgz
    - name: make
      run: time ./cov-analysis*/bin/cov-build --dir cov-int make -j2 || true
    - name: archive
      run: |
        time tar czvf ${{ secrets.COVERITY_PROJECT_NAME }}.tgz cov-int
        ls -alh *.tgz   
    - name: Coverity upload
      run: |
        curl --form token="${{ secrets.COVERITY_TOKEN_SPDK }}" \
             --form email="${{ secrets.COVERITY_EMAIL_ADDR }}" \
             --form file=@${{ secrets.COVERITY_PROJECT_NAME }}.tgz \
             --form version="$(date -u -I)-$(git rev-parse --short HEAD)" \
             --form description="analysis of $(git branch --show-current)" \
             https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT_NAME }}

